package PieNg::Model::PieDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PieDB::Schema',
    # login data is in the conf file.
);

=head1 NAME

PieNg::Model::PieDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PieNg>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PieDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Tim Howe

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
